/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_data_Alignment */

#ifndef _Included_jfftw_data_Alignment
#define _Included_jfftw_data_Alignment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_data_Alignment
 * Method:    jfftw_alignment_of
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_jfftw_data_Alignment_jfftw_1alignment_1of___3D
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     jfftw_data_Alignment
 * Method:    jfftw_alignment_of
 * Signature: (Ljava/nio/DoubleBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jfftw_data_Alignment_jfftw_1alignment_1of__Ljava_nio_DoubleBuffer_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
