/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_Plan */

#define _PRE_PLAN \
array_pair in = get_value_array(env, i); \
array_pair out = get_value_array(env, o);

#define _POST_PLAN \
release_array_pair(env, in, JNI_COMMIT); \
release_array_pair(env, out, JNI_COMMIT); \
return (jlong) p;

#ifndef _Included_jfftw_Plan
#define _Included_jfftw_Plan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_Plan
 * Method:    jfftw_fprint_plan
 * Signature: (Ljfftw/Plan;Ljava/io/File;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Plan_jfftw_1fprint_1plan
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_print_plan
 * Signature: (Ljfftw/Plan;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Plan_jfftw_1print_1plan
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_sprint_plan
 * Signature: (Ljfftw/Plan;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfftw_Plan_jfftw_1sprint_1plan
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft
 * Signature: (I[ILjfftw/Complex;Ljfftw/Complex;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_1d
 * Signature: (ILjfftw/Complex;Ljfftw/Complex;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_2d
 * Signature: (IILjfftw/Complex;Ljfftw/Complex;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_3d
 * Signature: (IIILjfftw/Complex;Ljfftw/Complex;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_c2r
 * Signature: (I[ILjfftw/Complex;Ljfftw/Real;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1c2r
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_c2r_1d
 * Signature: (ILjfftw/Complex;Ljfftw/Real;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1c2r_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_c2r_2d
 * Signature: (IILjfftw/Complex;Ljfftw/Real;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1c2r_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_c2r_3d
 * Signature: (IIILjfftw/Complex;Ljfftw/Real;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1c2r_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_r2c
 * Signature: (I[ILjfftw/Real;Ljfftw/Complex;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1r2c
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_r2c_1d
 * Signature: (ILjfftw/Real;Ljfftw/Complex;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1r2c_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_r2c_2d
 * Signature: (IILjfftw/Real;Ljfftw/Complex;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1r2c_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_Plan
 * Method:    jfftw_plan_dft_r2c_3d
 * Signature: (IIILjfftw/Real;Ljfftw/Complex;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_Plan_jfftw_1plan_1dft_1r2c_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
