/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_planning_DirectPlan */

#ifndef _Included_jfftw_planning_DirectPlan
#define _Included_jfftw_planning_DirectPlan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_execute_dft
 * Signature: (Ljfftw/planning/DirectPlan;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_DirectPlan_jfftw_1execute_1dft
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_execute_dft_c2r
 * Signature: (Ljfftw/planning/DirectPlan;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_DirectPlan_jfftw_1execute_1dft_1c2r
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_execute_dft_r2c
 * Signature: (Ljfftw/planning/DirectPlan;Ljava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_DirectPlan_jfftw_1execute_1dft_1r2c
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft
 * Signature: (I[ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_1d
 * Signature: (ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_2d
 * Signature: (IILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_3d
 * Signature: (IIILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_c2r
 * Signature: (I[ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1c2r
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_c2r_1d
 * Signature: (ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1c2r_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_c2r_2d
 * Signature: (IILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1c2r_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_c2r_3d
 * Signature: (IIILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1c2r_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_r2c
 * Signature: (I[ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1r2c
  (JNIEnv *, jclass, jint, jintArray, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_r2c_1d
 * Signature: (ILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1r2c_11d
  (JNIEnv *, jclass, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_r2c_2d
 * Signature: (IILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1r2c_12d
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jint);

/*
 * Class:     jfftw_planning_DirectPlan
 * Method:    jfftw_plan_dft_r2c_3d
 * Signature: (IIILjava/nio/DoubleBuffer;Ljava/nio/DoubleBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_DirectPlan_jfftw_1plan_1dft_1r2c_13d
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
