/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_planning_Wisdom */

#ifndef _Included_jfftw_planning_Wisdom
#define _Included_jfftw_planning_Wisdom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_export_wisdom_to_filename
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jfftw_planning_Wisdom_jfftw_1export_1wisdom_1to_1filename
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_export_wisdom_to_string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfftw_planning_Wisdom_jfftw_1export_1wisdom_1to_1string
  (JNIEnv *, jclass);

/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_forget_wisdom
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_Wisdom_jfftw_1forget_1wisdom
  (JNIEnv *, jclass);

/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_import_system_wisdom
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jfftw_planning_Wisdom_jfftw_1import_1system_1wisdom
  (JNIEnv *, jclass);

/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_import_wisdom_from_filename
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jfftw_planning_Wisdom_jfftw_1import_1wisdom_1from_1filename
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jfftw_planning_Wisdom
 * Method:    jfftw_import_wisdom_from_string
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_jfftw_planning_Wisdom_jfftw_1import_1wisdom_1from_1string
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
