/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_planning_Plan */

#ifndef _Included_jfftw_planning_Plan
#define _Included_jfftw_planning_Plan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_cost
 * Signature: (Ljfftw/planning/Plan;)D
 */
JNIEXPORT jdouble JNICALL Java_jfftw_planning_Plan_jfftw_1cost
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_destroy_plan
 * Signature: (Ljfftw/planning/Plan;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_Plan_jfftw_1destroy_1plan
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_estimate_cost
 * Signature: (Ljfftw/planning/Plan;)D
 */
JNIEXPORT jdouble JNICALL Java_jfftw_planning_Plan_jfftw_1estimate_1cost
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_execute
 * Signature: (Ljfftw/planning/Plan;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_Plan_jfftw_1execute
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_print_plan
 * Signature: (Ljfftw/planning/Plan;)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_Plan_jfftw_1print_1plan
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_planning_Plan
 * Method:    jfftw_sprint_plan
 * Signature: (Ljfftw/planning/Plan;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jfftw_planning_Plan_jfftw_1sprint_1plan
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
