/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_planning_PrimitivePlan */

#ifndef _Included_jfftw_planning_PrimitivePlan
#define _Included_jfftw_planning_PrimitivePlan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_execute_dft
 * Signature: (Ljfftw/planning/PrimitivePlan;[D[D)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1execute_1dft
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_execute_dft_c2r
 * Signature: (Ljfftw/planning/PrimitivePlan;[D[D)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1execute_1dft_1c2r
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_execute_dft_r2c
 * Signature: (Ljfftw/planning/PrimitivePlan;[D[D)V
 */
JNIEXPORT void JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1execute_1dft_1r2c
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft
 * Signature: (I[I[D[DII)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft
  (JNIEnv *, jclass, jint, jintArray, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_1d
 * Signature: (I[D[DII)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_11d
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_2d
 * Signature: (II[D[DII)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_12d
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_3d
 * Signature: (III[D[DII)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_13d
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_c2r
 * Signature: (I[I[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1c2r
  (JNIEnv *, jclass, jint, jintArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_c2r_1d
 * Signature: (I[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1c2r_11d
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_c2r_2d
 * Signature: (II[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1c2r_12d
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_c2r_3d
 * Signature: (III[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1c2r_13d
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_r2c
 * Signature: (I[I[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1r2c
  (JNIEnv *, jclass, jint, jintArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_r2c_1d
 * Signature: (I[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1r2c_11d
  (JNIEnv *, jclass, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_r2c_2d
 * Signature: (II[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1r2c_12d
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     jfftw_planning_PrimitivePlan
 * Method:    jfftw_plan_dft_r2c_3d
 * Signature: (III[D[DI)J
 */
JNIEXPORT jlong JNICALL Java_jfftw_planning_PrimitivePlan_jfftw_1plan_1dft_1r2c_13d
  (JNIEnv *, jclass, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
