/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_data_DirectAllocator */

#ifndef _Included_jfftw_data_DirectAllocator
#define _Included_jfftw_data_DirectAllocator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_data_DirectAllocator
 * Method:    jfftw_alloc_complex
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_jfftw_data_DirectAllocator_jfftw_1alloc_1complex
  (JNIEnv *, jclass, jint);

/*
 * Class:     jfftw_data_DirectAllocator
 * Method:    jfftw_alloc_real
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_jfftw_data_DirectAllocator_jfftw_1alloc_1real
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
