/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jfftw_Execution */

#define _PRE_EXECUTE \
fftw_plan p = get_fftw_plan(env, plan); \
array_pair in = get_value_array(env, i); \
array_pair out = get_value_array(env, o);

#define _POST_EXECUTE \
release_array_pair(env, in, JNI_COMMIT); \
release_array_pair(env, out, JNI_COMMIT);

#ifndef _Included_jfftw_Execution
#define _Included_jfftw_Execution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jfftw_Execution
 * Method:    jfftw_execute
 * Signature: (Ljfftw/Plan;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Execution_jfftw_1execute
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jfftw_Execution
 * Method:    jfftw_execute_dft
 * Signature: (Ljfftw/Plan;Ljfftw/Complex;Ljfftw/Complex;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Execution_jfftw_1execute_1dft
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_Execution
 * Method:    jfftw_execute_dft_c2r
 * Signature: (Ljfftw/Plan;Ljfftw/Complex;Ljfftw/Real;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Execution_jfftw_1execute_1dft_1c2r
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_Execution
 * Method:    jfftw_execute_dft_r2c
 * Signature: (Ljfftw/Plan;Ljfftw/Real;Ljfftw/Complex;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Execution_jfftw_1execute_1dft_1r2c
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jfftw_Execution
 * Method:    jfftw_execute_r2r
 * Signature: (Ljfftw/Plan;Ljfftw/Real;Ljfftw/Real;)V
 */
JNIEXPORT void JNICALL Java_jfftw_Execution_jfftw_1execute_1r2r
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
